wildfly/wildfly-github-bot

- pom.xml
- src/main/java/io/xstefank/wildlfy/bot/config/WildFlyConfigFile.java
- src/main/java/io/xstefank/wildlfy/bot/format/checks/TitleCheck.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> Add Checkstyle and delete useless lines

- pom.xml
> Update minimum JDK to 17

- README.md
- pom.xml
- src/main/resources/application.properties
> add openshift deployment

- src/main/java/io/xstefank/wildlfy/bot/config/util/Matcher.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
- src/test/resources/pr-opened.json
> Implement WildFlyRule#titleBody

- pom.xml
- src/test/java/io/xstefank/wildfly/bot/PRCommitsQuantityCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/PRDescriptionCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/PREditTest.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
- src/test/java/io/xstefank/wildfly/bot/PRTitleCheckTest.java
> Upgrade checkstyle to 3.3.0 to enable text blocks

- src/main/java/io/xstefank/wildlfy/bot/PullRequestFormatProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> Check PR format once PR is opened

- src/main/java/io/xstefank/wildlfy/bot/LifecycleProcessor.java
- src/main/java/io/xstefank/wildlfy/bot/PullRequestFormatProcessor.java
- src/main/java/io/xstefank/wildlfy/bot/TriagePullRequestProcessor.java
- src/main/java/io/xstefank/wildlfy/bot/config/RuntimeConstants.java
- src/main/java/io/xstefank/wildlfy/bot/config/WildFlyConfigFile.java
- src/test/java/io/xstefank/wildfly/bot/PREditTest.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
- src/test/java/io/xstefank/wildfly/bot/RuleMissingIdTest.java
Resolves #49 
In TriagePullRequestProcessor.java
@Valid annotation was not working in combination with @ConfigFile in method parameters. Maybe due to bug with nested Class. Hence a new method to invoke not null check with @Valid annotated parameter.
> Add mandatory id to rules & Update tests accordingly

- pom.xml
Bump version to LTS Quarkus version.
> Bump quarkus version 3.2.0.Final

- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/LifecycleProcessor.java
- src/main/java/io/xstefank/wildfly/bot/TriagePullRequestProcessor.java
- src/main/java/io/xstefank/wildfly/bot/config/WildFlyConfigFile.java
- src/test/java/io/xstefank/wildfly/bot/PRConfigFileChangeTest.java
- src/test/java/io/xstefank/wildfly/bot/StartupEventTest.java
* Remove mandatory id per rule
* Catch yaml parsing exceptions
* Apply all rules, log only rules with an id
* Update WildflyRule#toString
* Update tests accordingly
> Pre release update

- CONFIGURATION.yml
> Add file describing configuration file options

- src/main/resources/application.properties
> Add openshift configuration

- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
> Run format and config file validation on forced commits.

- README.md
- pom.xml
- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/LifecycleProcessor.java
- src/main/java/io/xstefank/wildfly/bot/model/WildFlyConfigFile.java
- src/main/resources/application.properties
- src/test/java/io/xstefank/wildfly/bot/StartupEventTest.java
> Email notifications on incorrect app deployment.

- src/main/java/io/xstefank/wildfly/bot/TriagePullRequestProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
> Implements check if user is already mentioned in the cc comment

- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/main/java/io/xstefank/wildfly/bot/TriagePullRequestProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PROpenedTest.java
Resolves #59
Also probably #56 is now obsolete after discussions?
> Remove initialization of format. Switch to RequestScope beans.

- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PRTriggerTest.java
> Run the application on Reopened and Ready for review

- src/main/java/io/xstefank/wildfly/bot/util/Matcher.java
- src/test/java/io/xstefank/wildfly/bot/PRRuleTitleBodyCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/PRRuleTitleCheckTest.java
> Fix regex processing for matching and add more tests

- src/main/java/io/xstefank/wildfly/bot/util/Matcher.java
- src/test/java/io/xstefank/wildfly/bot/PRRuleDirectoryHitTest.java
> Fix directory matching prefixes

- pom.xml
- src/test/java/io/xstefank/wildfly/bot/StartupEventTest.java
Resolves #138 . Please review @xstefank
> Fix problem with WARNING message in native.

- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/main/java/io/xstefank/wildfly/bot/format/CommitMessagesCheck.java
- src/main/java/io/xstefank/wildfly/bot/format/TitleCheck.java
- src/main/java/io/xstefank/wildfly/bot/model/RuntimeConstants.java
- src/main/java/io/xstefank/wildfly/bot/model/WildFlyConfigFile.java
- src/main/java/io/xstefank/wildfly/bot/util/Patterns.java
- src/test/java/io/xstefank/wildfly/bot/PRCommitCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/PRConfigFileChangeTest.java
- src/test/java/io/xstefank/wildfly/bot/PRDependabotTest.java
- src/test/java/io/xstefank/wildfly/bot/PRFormatOverrideProjectKeyTest.java
- src/test/java/io/xstefank/wildfly/bot/PRTitleCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/helper/MockedGHPullRequestProcessor.java
+ this would need to be updated https://github.com/wildfly/wildfly/blob/main/.github/wildfly-bot.yml#L283
to something like this:
```
- pattern: "https://issues.redhat.com/browse/WFLY-\\d+|https://issues.jboss.org/browse/WFLY-\\d+"
message: "The description must contain a link to the JIRA issue \n\"https://issues.redhat.com/browse/WFLY-XYZ\" (preferred) or \"https://issues.jboss.org/browse/WFLY-\\d+\""
```
please review @xstefank
> Expect only single issue mention in title / one of the commits

- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/main/java/io/xstefank/wildfly/bot/TriagePullRequestProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PRSkipPullRequestTest.java
> Allow to skip format with simple command.

- pom.xml
- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/main/java/io/xstefank/wildfly/bot/PullRequestRuleProcessor.java
- src/main/java/io/xstefank/wildfly/bot/util/GithubProcessor.java
- src/main/java/io/xstefank/wildfly/bot/util/PullRequestLogger.java
- src/test/java/io/xstefank/wildfly/bot/PRReviewAssignmentTest.java
- src/test/java/io/xstefank/wildfly/bot/PRSkipPullRequestTest.java
> Create custom logger prepending PR number

- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PRDependabotTest.java
Related to #161 . No checks for dependabot comment just yet
> Update dependabot message

- CONTRIBUTING.md
> Create contributing guide

- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/main/java/io/xstefank/wildfly/bot/model/Format.java
- src/test/java/io/xstefank/wildfly/bot/PRCommitCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/PRDescriptionCheckTest.java
- src/test/java/io/xstefank/wildfly/bot/PRTitleCheckTest.java
> Introduce option to globally disable format checks

- .github/workflows/maven.yml
- .mvn/wrapper/maven-wrapper.properties
- pom.xml
> Update Default JDK & quarkus version

- src/main/java/io/xstefank/wildfly/bot/ConfigFileChangeProcessor.java
- src/main/java/io/xstefank/wildfly/bot/PullRequestFormatProcessor.java
- src/test/java/io/xstefank/wildfly/bot/PRConfigFileChangeTest.java
- src/test/java/io/xstefank/wildfly/bot/PRSkipPullRequestTest.java
- src/test/java/io/xstefank/wildfly/bot/PRUpdateCommentOnEditTest.java
- src/test/java/io/xstefank/wildfly/bot/utils/MockedContext.java
- src/test/java/io/xstefank/wildfly/bot/utils/Util.java
> Remove format comment upon format check skip command edit

- README.md
> Update README with functionality

- .github/workflows/formatter.yml
> Add formatter GitHub action workflow

- .gitignore
- pom.xml
- src/main/resources/application.properties
> Specify Heap size, update .gitignore to ignore deploy.sh script

- src/main/java/org/wildfly/bot/PullRequestFormatProcessor.java
> Fix MissingFormatArgumentException in PullRequestFormatProcessor

- src/main/java/org/wildfly/bot/util/GithubProcessor.java
- src/test/java/org/wildfly/bot/webhooks/PRReviewAssignmentTest.java
> Add additional logging for debugging purpose of request reviewer intermittent issue

- README.md
Changed:
- wrong YAML file format/structure
- just overall formatting
- other
> Fixed mistakes in the README.md file

- src/main/resources/application.properties
> fix event polling setup

- src/test/java/org/wildfly/bot/PRAppendingMessageTest.java
- src/test/java/org/wildfly/bot/PRAutomaticLabelingTest.java
- src/test/java/org/wildfly/bot/PRChecksTest.java
- src/test/java/org/wildfly/bot/PRCommitCheckTest.java
- src/test/java/org/wildfly/bot/PRConfigFileChangeTest.java
- src/test/java/org/wildfly/bot/PRDependabotTest.java
- src/test/java/org/wildfly/bot/PRDescriptionCheckTest.java
- src/test/java/org/wildfly/bot/PRDirectoriesVerificationTest.java
- src/test/java/org/wildfly/bot/PRFormatOverrideProjectKeyTest.java
- src/test/java/org/wildfly/bot/PRMentionsReviewsCombinationTest.java
- src/test/java/org/wildfly/bot/PRNotifyChangeOnPREditTest.java
- src/test/java/org/wildfly/bot/PRReviewAssignmentTest.java
- src/test/java/org/wildfly/bot/PRReviewFixMeLabelTest.java
- src/test/java/org/wildfly/bot/PRRuleDescriptionCheckTest.java
- src/test/java/org/wildfly/bot/PRRuleDirectoryHitTest.java
- src/test/java/org/wildfly/bot/PRRuleLabelTest.java
- src/test/java/org/wildfly/bot/PRRuleNotifyTest.java
- src/test/java/org/wildfly/bot/PRRuleTitleBodyCheckTest.java
- src/test/java/org/wildfly/bot/PRRuleTitleCheckTest.java
- src/test/java/org/wildfly/bot/PRSkipPullRequestTest.java
- src/test/java/org/wildfly/bot/PRTitleCheckTest.java
- src/test/java/org/wildfly/bot/PRTriggerTest.java
- src/test/java/org/wildfly/bot/PRUpdateCommentOnEditTest.java
- src/test/java/org/wildfly/bot/PushEventTest.java
> Migrate tests from webhooks to root package

- src/main/java/org/wildfly/bot/util/GithubProcessor.java
> Fix remove labels log message in GithubProcessor
